name: rspec-loop CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby {{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build & Run Tests
        run: |
          bundle install --jobs 4
          bundle exec appraisal install
          bundle exec appraisal rake
